#!/bin/sh
# Write the Homebrew cask for a published fork release.
# Usage: fork/write-cask.sh <version> <sha256> <owner/repo>
set -eu

version=$1
sha256=$2
repository=$3
root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)

mkdir -p "$root/Casks"
cat > "$root/Casks/hex-openrouter.rb" <<EOF
# Generated by fork/write-cask.sh in .github/workflows/fork-release.yml.
cask "hex-openrouter" do
  version "$version"
  sha256 "$sha256"

  url "https://github.com/$repository/releases/download/fork-v#{version}/Hex-OpenRouter-#{version}.zip"
  name "Hex OpenRouter"
  desc "HEX voice dictation fork with OpenRouter transcription and model fallback"
  homepage "https://github.com/$repository"

  depends_on arch: :arm64
  depends_on macos: ">= :sequoia"

  app "Hex OpenRouter.app"

  # The build is signed ad hoc, not notarized: drop the download quarantine so
  # Gatekeeper does not refuse to open it.
  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{appdir}/Hex OpenRouter.app"]
  end

  zap trash: [
    "~/Library/Application Support/hex-openrouter",
  ]
end
EOF
