# Generated by scripts/release.py in .github/workflows/release.yml.
cask "endu" do
  version "4.0.1"
  sha256 "7f4a209ae4af4f19b39acf61b7d3a130714cd4486874eb00376d25dd8e5a4327"

  url "https://github.com/publi0/endu/releases/download/v#{version}/Endu-#{version}.zip"
  name "Endu"
  desc "Dictation with live transcription and speech provider fallback"
  homepage "https://github.com/publi0/endu"

  depends_on arch: :arm64
  depends_on macos: :sequoia

  app "Endu.app"

  # The build is not notarized by Apple.
  postflight_steps do
    run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{appdir}}/Endu.app"]
  end

  zap trash: [
    "~/Library/Application Support/hex-openrouter",
  ]
end
