# Generated by scripts/release.py in .github/workflows/release.yml.
cask "hex-openrouter" do
  version "3.0.1"
  sha256 "23c222d5239f7d972ec504fd0e5881f3f1f9de2432a0abac1f9c90bb8a281386"

  url "https://github.com/publi0/hex/releases/download/v#{version}/Hex-#{version}.zip"
  name "Hex"
  desc "Hold-to-talk dictation transcribed through OpenRouter with model fallback"
  homepage "https://github.com/publi0/hex"

  depends_on arch: :arm64
  depends_on macos: ">= :sequoia"

  app "Hex.app"

  # The build is signed ad hoc, not notarized.
  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{appdir}/Hex.app"]
  end

  zap trash: [
    "~/Library/Application Support/hex-openrouter",
  ]
end
