# Generated by scripts/release.py in .github/workflows/release.yml.
cask "hex-openrouter" do
  version "3.0.5"
  sha256 "a4120b7c17e2a4c315356472f1227f262bf9f99e96e73ba81c4228d0bada5088"

  url "https://github.com/publi0/hex/releases/download/v#{version}/Hex-#{version}.zip"
  name "Hex"
  desc "Hold-to-talk dictation transcribed through OpenRouter with model fallback"
  homepage "https://github.com/publi0/hex"

  depends_on arch: :arm64
  depends_on macos: ">= :sequoia"

  app "Hex.app"

  # The build is not notarized by Apple.
  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{appdir}/Hex.app"]
  end

  zap trash: [
    "~/Library/Application Support/hex-openrouter",
  ]
end
