# Generated by scripts/release.py in .github/workflows/release.yml.
cask "hex-openrouter" do
  version "3.1.1"
  sha256 "4612fb1b2868013748c25e689c6080877f6819d8713f86a33e6885b73307d810"

  url "https://github.com/publi0/hex/releases/download/v#{version}/Hex-#{version}.zip"
  name "Hex"
  desc "Hold-to-talk dictation transcribed through OpenRouter with model fallback"
  homepage "https://github.com/publi0/hex"

  depends_on arch: :arm64
  depends_on macos: ">= :sequoia"

  app "Hex.app"

  # The build is not notarized by Apple.
  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{appdir}/Hex.app"]
  end

  zap trash: [
    "~/Library/Application Support/hex-openrouter",
  ]
end
