#!/usr/bin/env python3
"""Publish explicit Cargo versions and reconcile the Homebrew cask. Python 3.11+."""

import argparse
import hashlib
import json
import os
from pathlib import Path
import plistlib
import re
import subprocess
import tempfile
import time
import tomllib
import zipfile

from code_signing import CERTIFICATE, verify_archive


CASK = Path("Casks/hex-openrouter.rb")
VERSION = re.compile(r"(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)")


def version_tuple(version):
    match = VERSION.fullmatch(version)
    if not match:
        raise ValueError(f"Expected a stable version X.Y.Z, got {version!r}")
    return tuple(map(int, match.groups()))


def cargo_version(text):
    version = tomllib.loads(text)["package"]["version"]
    version_tuple(version)
    return version


def run(*args, cwd=None, check=True):
    result = subprocess.run(args, cwd=cwd, text=True, capture_output=True)
    if check and result.returncode:
        raise RuntimeError(f"{args[0]} failed: {result.stderr.strip()}")
    return result


def stable_releases(releases):
    for release in releases:
        tag = release["tag_name"]
        if not release["draft"] and not release["prerelease"] and tag.startswith("v"):
            if VERSION.fullmatch(tag[1:]):
                yield version_tuple(tag[1:])


def release_plan(version, releases):
    current = next((item for item in releases if item["tag_name"] == f"v{version}"), None)
    if current and not current["draft"]:
        if current["prerelease"]:
            raise ValueError(f"v{version} already exists as a prerelease")
        return {"version": version, "build": "false", "skip": "false"}
    newer = any(item > version_tuple(version) for item in stable_releases(releases))
    return {"version": version, "build": str(not newer).lower(), "skip": str(newer).lower()}


def archive_checksum(archive, version, expected_digest=None):
    if archive.name != f"Hex-{version}.zip":
        raise ValueError("Archive name does not match the Cargo version")
    checksum = hashlib.sha256(archive.read_bytes()).hexdigest()
    if expected_digest and expected_digest != f"sha256:{checksum}":
        raise ValueError("Downloaded asset does not match its GitHub digest")
    with zipfile.ZipFile(archive) as bundle:
        plist = plistlib.loads(bundle.read("Hex.app/Contents/Info.plist"))
        if plist.get("CFBundleShortVersionString") != version:
            raise ValueError("App version does not match the release version")
        if plist.get("CFBundleIdentifier") != "dev.publio.hex-openrouter":
            raise ValueError("Unexpected app bundle identifier")
        if bundle.getinfo("Hex.app/Contents/MacOS/hex").file_size == 0:
            raise ValueError("App executable is empty")
    return checksum


def render_cask(version, checksum, repository):
    version_tuple(version)
    if not re.fullmatch(r"[0-9a-f]{64}", checksum):
        raise ValueError("Invalid SHA-256")
    if not re.fullmatch(r"[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+", repository):
        raise ValueError("Invalid GitHub repository")
    return f'''# Generated by scripts/release.py in .github/workflows/release.yml.
cask "hex-openrouter" do
  version "{version}"
  sha256 "{checksum}"

  url "https://github.com/{repository}/releases/download/v#{{version}}/Hex-#{{version}}.zip"
  name "Hex"
  desc "Hold-to-talk dictation transcribed through OpenRouter with model fallback"
  homepage "https://github.com/{repository}"

  depends_on arch: :arm64
  depends_on macos: :sequoia

  app "Hex.app"

  # The build is not notarized by Apple.
  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{{appdir}}/Hex.app"]
  end

  zap trash: [
    "~/Library/Application Support/hex-openrouter",
  ]
end
'''


def cask_version(text):
    match = re.search(r'^\s*version "([^"]+)"', text, re.MULTILINE)
    if not match:
        raise ValueError("Cannot read the current cask version")
    # The last old release used X.Y.Z-run; its numeric base precedes 3.0.0.
    return version_tuple(match[1].split("-", 1)[0])


class GitHub:
    def __init__(self, repository):
        self.repository = repository

    def releases(self):
        result = run("gh", "api", "--paginate", "--slurp",
                     f"repos/{self.repository}/releases?per_page=100")
        return [release for page in json.loads(result.stdout) for release in page]

    def create_draft(self, tag, source):
        notes = f"Built from {source}. Install or update with `brew upgrade --cask hex-openrouter`.\n"
        with tempfile.NamedTemporaryFile(mode="w", suffix=".json") as body:
            json.dump({"tag_name": tag, "target_commitish": source,
                       "name": f"Hex {tag[1:]}", "body": notes,
                       "draft": True, "prerelease": False}, body)
            body.flush()
            result = run("gh", "api", "--method", "POST",
                         f"repos/{self.repository}/releases", "--input", body.name)
        return json.loads(result.stdout)

    def get_release(self, release_id):
        result = run("gh", "api", f"repos/{self.repository}/releases/{release_id}")
        return json.loads(result.stdout)

    def upload(self, tag, archive):
        run("gh", "release", "upload", tag, str(archive), "--repo", self.repository)

    def delete_incomplete_asset(self, tag, name):
        run("gh", "release", "delete-asset", tag, name, "--yes", "--repo", self.repository)

    def download(self, tag, name, directory):
        run("gh", "release", "download", tag, "--repo", self.repository,
            "--pattern", name, "--dir", str(directory))
        return directory / name

    def publish(self, tag, latest):
        run("gh", "release", "edit", tag, "--repo", self.repository,
            "--draft=false", f"--latest={str(latest).lower()}")


class Publisher:
    def __init__(self, root, repository, github=None):
        self.root = root
        self.repository = repository
        self.github = github or GitHub(repository)
        self.version = cargo_version((root / "Cargo.toml").read_text())
        self.tag = f"v{self.version}"
        self.source = self.git("rev-parse", "HEAD").stdout.strip()

    def git(self, *args, check=True):
        return run("git", *args, cwd=self.root, check=check)

    def plan(self):
        return release_plan(self.version, self.github.releases())

    def tag_commit(self):
        refs = self.git("ls-remote", "--tags", "origin", f"refs/tags/{self.tag}",
                        f"refs/tags/{self.tag}^{{}}").stdout.splitlines()
        if not refs:
            return None
        # An annotated tag's peeled commit sorts after its tag object.
        return sorted(refs, key=lambda line: line.split()[1])[-1].split()[0]

    def ensure_source_tag(self):
        manifest = self.git("show", f"{self.source}:Cargo.toml").stdout
        if cargo_version(manifest) != self.version:
            raise ValueError("Cargo version is not committed at the release source")
        existing = self.tag_commit()
        if existing and existing != self.source:
            raise ValueError(f"{self.tag} already points to a different source commit")
        if not existing:
            # Explicit refs prevent GitHub from choosing a newer default-branch tip.
            self.git("push", "origin", f"{self.source}:refs/tags/{self.tag}")

    def verify_published_source(self):
        if not self.tag_commit():
            raise ValueError("Published release is missing its source tag")
        self.git("fetch", "--no-tags", "origin", f"refs/tags/{self.tag}")
        manifest = self.git("show", "FETCH_HEAD:Cargo.toml").stdout
        if cargo_version(manifest) != self.version:
            raise ValueError("Published tag's Cargo version does not match the release")

    def publish(self):
        releases = self.github.releases()
        plan = release_plan(self.version, releases)
        if plan["skip"] == "true":
            print(f"Skipping {self.tag}: a newer version has already been published")
            return
        release = next((item for item in releases if item["tag_name"] == self.tag), None)
        published = release is not None and not release["draft"]
        if published:
            self.verify_published_source()
        else:
            archive = self.root / "target" / "app" / f"Hex-{self.version}.zip"
            archive_checksum(archive, self.version)
            self.ensure_source_tag()
            if release is None:
                # The create response is authoritative before the list endpoint catches up.
                release = self.github.create_draft(self.tag, self.source)
            asset = self.find_asset(release)
            if asset and (asset.get("state") != "uploaded" or asset.get("size", 0) == 0):
                self.github.delete_incomplete_asset(self.tag, asset["name"])
                asset = None
            if asset is None:
                self.github.upload(self.tag, archive)
                release = self.wait_for_asset(release["id"])

        asset = self.find_asset(release)
        if not asset or asset.get("state") != "uploaded" or asset.get("size", 0) == 0:
            raise ValueError(f"{self.tag} has no complete app archive")
        with tempfile.TemporaryDirectory(prefix="hex-release-") as temporary:
            downloaded = self.github.download(self.tag, asset["name"], Path(temporary))
            checksum = archive_checksum(downloaded, self.version, asset.get("digest"))
            if version_tuple(self.version) >= (3, 0, 5):
                # Check the actual remote asset, including resumed drafts.
                verify_archive(downloaded, self.root / CERTIFICATE)
        if not published:
            newer = any(item > version_tuple(self.version)
                        for item in stable_releases(self.github.releases()))
            self.github.publish(self.tag, latest=not newer)
        self.update_cask(checksum)

    def wait_for_asset(self, release_id):
        last_error = None
        for attempt in range(5):
            try:
                release = self.github.get_release(release_id)
                asset = self.find_asset(release)
                if asset and asset.get("state") == "uploaded" and asset.get("size", 0) > 0:
                    return release
            except RuntimeError as error:
                last_error = error
            if attempt < 4:
                time.sleep(min(0.5 * 2 ** attempt, 2))
        raise RuntimeError(
            f"Uploaded archive for {self.tag} is not readable yet; rerun to resume the draft"
        ) from last_error

    def find_asset(self, release):
        name = f"Hex-{self.version}.zip"
        return next((item for item in release["assets"] if item["name"] == name), None)

    def update_cask(self, checksum):
        content = render_cask(self.version, checksum, self.repository)
        for _ in range(3):
            self.git("fetch", "origin", "refs/heads/main")
            current = self.git("show", f"FETCH_HEAD:{CASK}").stdout
            if cask_version(current) > version_tuple(self.version):
                print(f"Keeping newer Homebrew version; {self.tag} is already published")
                return
            if current == content:
                print(f"Homebrew already points to {self.tag}")
                return
            self.git("checkout", "-B", "release-cask", "FETCH_HEAD")
            (self.root / CASK).write_text(content)
            self.git("add", str(CASK))
            self.git("-c", "user.name=github-actions[bot]", "-c",
                     "user.email=41898282+github-actions[bot]@users.noreply.github.com",
                     "commit", "-m", f"chore(cask): Hex {self.version}")
            result = self.git("push", "origin", "HEAD:refs/heads/main", check=False)
            if result.returncode == 0:
                return
            # Main advanced: regenerate only the cask on its new tip. Never force push.
        raise RuntimeError("Release is published, but cask update failed; rerun to reconcile")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    commands = parser.add_subparsers(dest="command", required=True)
    commands.add_parser("version")
    commands.add_parser("plan")
    commands.add_parser("publish")
    writer = commands.add_parser("write-cask")
    writer.add_argument("version")
    writer.add_argument("checksum")
    writer.add_argument("repository")
    args = parser.parse_args()
    root = Path(__file__).resolve().parent.parent
    if args.command == "version":
        print(cargo_version((root / "Cargo.toml").read_text()))
    elif args.command == "write-cask":
        (root / CASK).write_text(render_cask(args.version, args.checksum, args.repository))
    else:
        repository = os.environ["GH_REPO"]
        publisher = Publisher(root, repository)
        if args.command == "plan":
            plan = publisher.plan()
            print(json.dumps(plan))
            with open(os.environ["GITHUB_OUTPUT"], "a") as output:
                for key, value in plan.items():
                    output.write(f"{key}={value}\n")
        else:
            publisher.publish()


if __name__ == "__main__":
    main()
